name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Daily metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
          GH_TOKEN: ${{ secrets.SECRET }}
          SHOW_LINES_OF_CODE: False
          SHOW_COMMIT: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
  github-metrics:
      name: Monthly metrics
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.wakatime.svg
            token: NOT_NEEDED
            base: ""
            plugin_wakatime: yes
            plugin_wakatime_days: 30
            plugin_wakatime_limit: 3
            plugin_wakatime_sections: time, languages, os
            plugin_wakatime_token: ${{ secrets.WAKATIME }}
