name: Metrics
on: 
  workflow_dispatch:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: "365"
          plugin_wakatime_limit: 3
          plugin_wakatime_sections: time, projects-graphs, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME }}
